Handled failed download

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -14,7 +14,13 @@ CASSANDRA_DOWNLOAD_URL=${CASSANDRA_DOWNLOAD_URL:-http://apache.claz.org/cassandr
 basename=$(basename $CASSANDRA_DOWNLOAD_URL)
 
 echo "-----> Downloading & unpacking cassandra"
-mkdir -p ${BUILD_DIR}/.cassandra && cd ${BUILD_DIR}/.cassandra && curl -q $CASSANDRA_DOWNLOAD_URL > $basename && tar zxf $basename && rm $basename
+mkdir -p ${BUILD_DIR}/.cassandra && cd ${BUILD_DIR}/.cassandra && curl -f -q $CASSANDRA_DOWNLOAD_URL > $basename && tar zxf $basename && rm $basename
+
+rc=$?
+if [[ $rc != 0 ]]; then
+    echo "-----> Unable to download ${CASSANDRA_DOWNLOAD_URL}"
+    exit $rc;
+fi
 
 echo "-----> Installing cqlsh"
 cd ${BUILD_DIR}/.cassandra/* && rm -rf *.txt lib/*.jar conf doc interface javadoc tools
